---
- name: Media Wiki Database and WebServer 
  hosts: all
  become: yes
  
  # Extra Vars passed from the command line
  vars_files: 
    - vault.yaml

  roles:
   - { role: mysqldb, tags: ['install_db'] }
   - { role: web, tags: [ 'install_web' ] }
